/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables.records;


import com.pokemon.db.tables.Move;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoveRecord extends UpdatableRecordImpl<MoveRecord> implements Record5<String, Integer, String, String, String> {

	private static final long serialVersionUID = -523648641;

	/**
	 * Setter for <code>public.move.name</code>.
	 */
	public MoveRecord setName(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.move.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.move.strength</code>.
	 */
	public MoveRecord setStrength(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.move.strength</code>.
	 */
	public Integer getStrength() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.move.effect</code>.
	 */
	public MoveRecord setEffect(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.move.effect</code>.
	 */
	public String getEffect() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.move.description</code>.
	 */
	public MoveRecord setDescription(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.move.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.move.type</code>.
	 */
	public MoveRecord setType(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.move.type</code>.
	 */
	public String getType() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, Integer, String, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, Integer, String, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Move.MOVE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Move.MOVE.STRENGTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Move.MOVE.EFFECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Move.MOVE.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Move.MOVE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getStrength();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getEffect();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoveRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoveRecord value2(Integer value) {
		setStrength(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoveRecord value3(String value) {
		setEffect(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoveRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoveRecord value5(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoveRecord values(String value1, Integer value2, String value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MoveRecord
	 */
	public MoveRecord() {
		super(Move.MOVE);
	}

	/**
	 * Create a detached, initialised MoveRecord
	 */
	public MoveRecord(String name, Integer strength, String effect, String description, String type) {
		super(Move.MOVE);

		setValue(0, name);
		setValue(1, strength);
		setValue(2, effect);
		setValue(3, description);
		setValue(4, type);
	}
}
