/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables.records;


import com.pokemon.db.tables.Pokemon;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PokemonRecord extends UpdatableRecordImpl<PokemonRecord> implements Record10<String, Integer, Integer, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = 523598303;

	/**
	 * Setter for <code>public.pokemon.name</code>.
	 */
	public PokemonRecord setName(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.pokemon.pokedex_num</code>.
	 */
	public PokemonRecord setPokedexNum(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.pokedex_num</code>.
	 */
	public Integer getPokedexNum() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.pokemon.evolves_to</code>.
	 */
	public PokemonRecord setEvolvesTo(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.evolves_to</code>.
	 */
	public Integer getEvolvesTo() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.pokemon.type1</code>.
	 */
	public PokemonRecord setType1(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.type1</code>.
	 */
	public String getType1() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.pokemon.type2</code>.
	 */
	public PokemonRecord setType2(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.type2</code>.
	 */
	public String getType2() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.pokemon.move1</code>.
	 */
	public PokemonRecord setMove1(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.move1</code>.
	 */
	public String getMove1() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.pokemon.move2</code>.
	 */
	public PokemonRecord setMove2(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.move2</code>.
	 */
	public String getMove2() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.pokemon.move3</code>.
	 */
	public PokemonRecord setMove3(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.move3</code>.
	 */
	public String getMove3() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.pokemon.move4</code>.
	 */
	public PokemonRecord setMove4(String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.move4</code>.
	 */
	public String getMove4() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.pokemon.sprite</code>.
	 */
	public PokemonRecord setSprite(String value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>public.pokemon.sprite</code>.
	 */
	public String getSprite() {
		return (String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, Integer, Integer, String, String, String, String, String, String, String> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, Integer, Integer, String, String, String, String, String, String, String> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Pokemon.POKEMON.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Pokemon.POKEMON.POKEDEX_NUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Pokemon.POKEMON.EVOLVES_TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Pokemon.POKEMON.TYPE1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Pokemon.POKEMON.TYPE2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Pokemon.POKEMON.MOVE1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Pokemon.POKEMON.MOVE2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Pokemon.POKEMON.MOVE3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Pokemon.POKEMON.MOVE4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Pokemon.POKEMON.SPRITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPokedexNum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getEvolvesTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getType1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getType2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getMove1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getMove2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getMove3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getMove4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSprite();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value2(Integer value) {
		setPokedexNum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value3(Integer value) {
		setEvolvesTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value4(String value) {
		setType1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value5(String value) {
		setType2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value6(String value) {
		setMove1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value7(String value) {
		setMove2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value8(String value) {
		setMove3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value9(String value) {
		setMove4(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord value10(String value) {
		setSprite(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PokemonRecord values(String value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PokemonRecord
	 */
	public PokemonRecord() {
		super(Pokemon.POKEMON);
	}

	/**
	 * Create a detached, initialised PokemonRecord
	 */
	public PokemonRecord(String name, Integer pokedexNum, Integer evolvesTo, String type1, String type2, String move1, String move2, String move3, String move4, String sprite) {
		super(Pokemon.POKEMON);

		setValue(0, name);
		setValue(1, pokedexNum);
		setValue(2, evolvesTo);
		setValue(3, type1);
		setValue(4, type2);
		setValue(5, move1);
		setValue(6, move2);
		setValue(7, move3);
		setValue(8, move4);
		setValue(9, sprite);
	}
}
