/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables.records;


import com.pokemon.db.tables.StrongAgainst;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrongAgainstRecord extends UpdatableRecordImpl<StrongAgainstRecord> implements Record2<String, String> {

	private static final long serialVersionUID = -480463121;

	/**
	 * Setter for <code>public.strong_against.weak_type</code>.
	 */
	public StrongAgainstRecord setWeakType(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.strong_against.weak_type</code>.
	 */
	public String getWeakType() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.strong_against.strong_type</code>.
	 */
	public StrongAgainstRecord setStrongType(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.strong_against.strong_type</code>.
	 */
	public String getStrongType() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return StrongAgainst.STRONG_AGAINST.WEAK_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return StrongAgainst.STRONG_AGAINST.STRONG_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getWeakType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getStrongType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StrongAgainstRecord value1(String value) {
		setWeakType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StrongAgainstRecord value2(String value) {
		setStrongType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StrongAgainstRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StrongAgainstRecord
	 */
	public StrongAgainstRecord() {
		super(StrongAgainst.STRONG_AGAINST);
	}

	/**
	 * Create a detached, initialised StrongAgainstRecord
	 */
	public StrongAgainstRecord(String weakType, String strongType) {
		super(StrongAgainst.STRONG_AGAINST);

		setValue(0, weakType);
		setValue(1, strongType);
	}
}
