/**
 * This class is generated by jOOQ
 */
package com.thirdchannel.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class People implements Serializable {

	private static final long serialVersionUID = 1181747223;

	private final String firstName;
	private final String lastName;

	public People(People value) {
		this.firstName = value.firstName;
		this.lastName = value.lastName;
	}

	public People(
		String firstName,
		String lastName
	) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("People (");

		sb.append(firstName);
		sb.append(", ").append(lastName);

		sb.append(")");
		return sb.toString();
	}
}
