/**
 * This class is generated by jOOQ
 */
package com.thirdchannel.db.tables;


import com.thirdchannel.db.Public;
import com.thirdchannel.db.tables.records.PeopleRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class People extends TableImpl<PeopleRecord> {

	private static final long serialVersionUID = 924510675;

	/**
	 * The reference instance of <code>public.people</code>
	 */
	public static final People PEOPLE = new People();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PeopleRecord> getRecordType() {
		return PeopleRecord.class;
	}

	/**
	 * The column <code>public.people.first_name</code>.
	 */
	public final TableField<PeopleRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.people.last_name</code>.
	 */
	public final TableField<PeopleRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>public.people</code> table reference
	 */
	public People() {
		this("people", null);
	}

	/**
	 * Create an aliased <code>public.people</code> table reference
	 */
	public People(String alias) {
		this(alias, PEOPLE);
	}

	private People(String alias, Table<PeopleRecord> aliased) {
		this(alias, aliased, null);
	}

	private People(String alias, Table<PeopleRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public People as(String alias) {
		return new People(alias, this);
	}

	/**
	 * Rename this table
	 */
	public People rename(String name) {
		return new People(name, null);
	}
}
