/**
 * This class is generated by jOOQ
 */
package com.thirdchannel.db.tables;


import com.thirdchannel.db.Keys;
import com.thirdchannel.db.Public;
import com.thirdchannel.db.tables.records.People2Record;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class People2 extends TableImpl<People2Record> {

	private static final long serialVersionUID = -994296253;

	/**
	 * The reference instance of <code>public.people2</code>
	 */
	public static final People2 PEOPLE2 = new People2();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<People2Record> getRecordType() {
		return People2Record.class;
	}

	/**
	 * The column <code>public.people2.id</code>.
	 */
	public final TableField<People2Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.people2.first_name</code>.
	 */
	public final TableField<People2Record, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.people2.last_name</code>.
	 */
	public final TableField<People2Record, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.people2.age</code>.
	 */
	public final TableField<People2Record, Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.people2</code> table reference
	 */
	public People2() {
		this("people2", null);
	}

	/**
	 * Create an aliased <code>public.people2</code> table reference
	 */
	public People2(String alias) {
		this(alias, PEOPLE2);
	}

	private People2(String alias, Table<People2Record> aliased) {
		this(alias, aliased, null);
	}

	private People2(String alias, Table<People2Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<People2Record, Integer> getIdentity() {
		return Keys.IDENTITY_PEOPLE2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<People2Record> getPrimaryKey() {
		return Keys.PEOPLE2_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<People2Record>> getKeys() {
		return Arrays.<UniqueKey<People2Record>>asList(Keys.PEOPLE2_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public People2 as(String alias) {
		return new People2(alias, this);
	}

	/**
	 * Rename this table
	 */
	public People2 rename(String name) {
		return new People2(name, null);
	}
}
