spring:

  datasource:
    driverClassName:               org.postgresql.Driver
    initialSize:                   5
    logAbandoned:                  false
    maxActive:                     100
    maxIdle:                       100
    maxWait:                       30000
    minEvictableIdleTimeMillis:    60000
    minIdle:                       10
    removeAbandoned:               false
    removeAbandonedTimeout:        60
    testOnBorrow:                  true
    testOnReturn:                  false
    testWhileIdle:                 true
    timeBetweenEvictionRunsMillis: 5000
    validationInterval:            30000
    validationQuery:               select 1
    # Tomcat JDBC Enhanced Attributes
    abandonWhenPercentageFull:     0
    alternateUsernameAllowed:      false
    # TRANSACTION_READ_COMMITTED
    defaultTransactionIsolation:   2
    fairQueue:                     true
    jdbcInterceptors:              ConnectionState
    jmxEnabled:                    true
    maxAge:                        0
    suspectTimeout:                0
    useEquals:                     true
    url:      jdbc:postgresql://localhost/pokemon
    username: admin
    password: admin


logging:
  level:
    org.jooq: INFO
    com.pokemon: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework.security: DEBUG


---

spring:
  profiles: dev

  datasource:
    url:      jdbc:postgresql://localhost/pokemon
    username: admin
    password: admin
