/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables;


import com.pokemon.db.Keys;
import com.pokemon.db.Public;
import com.pokemon.db.tables.records.TrainsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trains extends TableImpl<TrainsRecord> {

	private static final long serialVersionUID = 360391506;

	/**
	 * The reference instance of <code>public.trains</code>
	 */
	public static final Trains TRAINS = new Trains();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TrainsRecord> getRecordType() {
		return TrainsRecord.class;
	}

	/**
	 * The column <code>public.trains.pokedex_num</code>.
	 */
	public final TableField<TrainsRecord, Integer> POKEDEX_NUM = createField("pokedex_num", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.trains.tid</code>.
	 */
	public final TableField<TrainsRecord, Integer> TID = createField("tid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.trains</code> table reference
	 */
	public Trains() {
		this("trains", null);
	}

	/**
	 * Create an aliased <code>public.trains</code> table reference
	 */
	public Trains(String alias) {
		this(alias, TRAINS);
	}

	private Trains(String alias, Table<TrainsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Trains(String alias, Table<TrainsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TrainsRecord> getPrimaryKey() {
		return Keys.TRAINS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TrainsRecord>> getKeys() {
		return Arrays.<UniqueKey<TrainsRecord>>asList(Keys.TRAINS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TrainsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TrainsRecord, ?>>asList(Keys.TRAINS__TRAINS_POKEDEX_NUM_FKEY, Keys.TRAINS__TRAINS_TID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Trains as(String alias) {
		return new Trains(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Trains rename(String name) {
		return new Trains(name, null);
	}
}
