/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables;


import com.pokemon.db.Keys;
import com.pokemon.db.Public;
import com.pokemon.db.tables.records.TypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Type extends TableImpl<TypeRecord> {

	private static final long serialVersionUID = 569744714;

	/**
	 * The reference instance of <code>public.type</code>
	 */
	public static final Type TYPE = new Type();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TypeRecord> getRecordType() {
		return TypeRecord.class;
	}

	/**
	 * The column <code>public.type.name</code>.
	 */
	public final TableField<TypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * Create a <code>public.type</code> table reference
	 */
	public Type() {
		this("type", null);
	}

	/**
	 * Create an aliased <code>public.type</code> table reference
	 */
	public Type(String alias) {
		this(alias, TYPE);
	}

	private Type(String alias, Table<TypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Type(String alias, Table<TypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TypeRecord> getPrimaryKey() {
		return Keys.TYPE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TypeRecord>> getKeys() {
		return Arrays.<UniqueKey<TypeRecord>>asList(Keys.TYPE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Type as(String alias) {
		return new Type(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Type rename(String name) {
		return new Type(name, null);
	}
}
