/**
 * This class is generated by jOOQ
 */
package com.thirdchannel.db;


import com.thirdchannel.db.tables.People2;
import com.thirdchannel.db.tables.records.People2Record;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<People2Record, Integer> IDENTITY_PEOPLE2 = Identities0.IDENTITY_PEOPLE2;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<People2Record> PEOPLE2_PKEY = UniqueKeys0.PEOPLE2_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<People2Record, Integer> IDENTITY_PEOPLE2 = createIdentity(People2.PEOPLE2, People2.PEOPLE2.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<People2Record> PEOPLE2_PKEY = createUniqueKey(People2.PEOPLE2, People2.PEOPLE2.ID);
	}
}
