/**
 * This class is generated by jOOQ
 */
package com.thirdchannel.db;


import com.thirdchannel.db.tables.People;
import com.thirdchannel.db.tables.People2;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.people
	 */
	public static final People PEOPLE = com.thirdchannel.db.tables.People.PEOPLE;

	/**
	 * The table public.people2
	 */
	public static final People2 PEOPLE2 = com.thirdchannel.db.tables.People2.PEOPLE2;
}
