/**
 * This class is generated by jOOQ
 */
package com.pokemon.db;


import com.pokemon.db.tables.Move;
import com.pokemon.db.tables.Pokemon;
import com.pokemon.db.tables.StrongAgainst;
import com.pokemon.db.tables.Trainer;
import com.pokemon.db.tables.Trains;
import com.pokemon.db.tables.Type;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = 1660746157;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.TRAINER_TID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Move.MOVE,
			Pokemon.POKEMON,
			StrongAgainst.STRONG_AGAINST,
			Trainer.TRAINER,
			Trains.TRAINS,
			Type.TYPE);
	}
}
