/**
 * This class is generated by jOOQ
 */
package com.pokemon.db;


import com.pokemon.db.tables.Move;
import com.pokemon.db.tables.Pokemon;
import com.pokemon.db.tables.StrongAgainst;
import com.pokemon.db.tables.Trainer;
import com.pokemon.db.tables.Trains;
import com.pokemon.db.tables.Type;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.move
	 */
	public static final Move MOVE = com.pokemon.db.tables.Move.MOVE;

	/**
	 * The table public.pokemon
	 */
	public static final Pokemon POKEMON = com.pokemon.db.tables.Pokemon.POKEMON;

	/**
	 * The table public.strong_against
	 */
	public static final StrongAgainst STRONG_AGAINST = com.pokemon.db.tables.StrongAgainst.STRONG_AGAINST;

	/**
	 * The table public.trainer
	 */
	public static final Trainer TRAINER = com.pokemon.db.tables.Trainer.TRAINER;

	/**
	 * The table public.trains
	 */
	public static final Trains TRAINS = com.pokemon.db.tables.Trains.TRAINS;

	/**
	 * The table public.type
	 */
	public static final Type TYPE = com.pokemon.db.tables.Type.TYPE;
}
