/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrongAgainst implements Serializable {

	private static final long serialVersionUID = 1832456915;

	private final String weakType;
	private final String strongType;

	public StrongAgainst(StrongAgainst value) {
		this.weakType = value.weakType;
		this.strongType = value.strongType;
	}

	public StrongAgainst(
		String weakType,
		String strongType
	) {
		this.weakType = weakType;
		this.strongType = strongType;
	}

	public String getWeakType() {
		return this.weakType;
	}

	public String getStrongType() {
		return this.strongType;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("StrongAgainst (");

		sb.append(weakType);
		sb.append(", ").append(strongType);

		sb.append(")");
		return sb.toString();
	}
}
