/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.2"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trains implements Serializable {

	private static final long serialVersionUID = 55975285;

	Integer pokedexNum;
	Integer tid;

	public Trains() {}

	public Trains(Trains value) {
		this.pokedexNum = value.pokedexNum;
		this.tid = value.tid;
	}

	public Trains(
			Integer pokedexNum,
			Integer tid
	) {
		this.pokedexNum = pokedexNum;
		this.tid = tid;
	}

	public Integer getPokedexNum() {
		return this.pokedexNum;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setPokedexNum(Integer pokedexNum) { this.pokedexNum = pokedexNum; }
	public void setTid(Integer tid) { this.tid = tid; }

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Trains (");

		sb.append(pokedexNum);
		sb.append(", ").append(tid);

		sb.append(")");
		return sb.toString();
	}
}