/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables.pojos;


import com.pokemon.db.enums.Gender;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trainer implements Serializable {

	private static final long serialVersionUID = -741477151;

	private final String  name;
	private final Integer tid;
	private final Gender  gender;
	private final Integer age;
	private final String  username;

	public Trainer(Trainer value) {
		this.name = value.name;
		this.tid = value.tid;
		this.gender = value.gender;
		this.age = value.age;
		this.username = value.username;
	}

	public Trainer(
		String  name,
		Integer tid,
		Gender  gender,
		Integer age,
		String  username
	) {
		this.name = name;
		this.tid = tid;
		this.gender = gender;
		this.age = age;
		this.username = username;
	}

	public String getName() {
		return this.name;
	}

	public Integer getTid() {
		return this.tid;
	}

	public Gender getGender() {
		return this.gender;
	}

	public Integer getAge() {
		return this.age;
	}

	public String getUsername() {
		return this.username;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Trainer (");

		sb.append(name);
		sb.append(", ").append(tid);
		sb.append(", ").append(gender);
		sb.append(", ").append(age);
		sb.append(", ").append(username);

		sb.append(")");
		return sb.toString();
	}
}
