/**
 * This class is generated by jOOQ
 */
package com.pokemon.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Type implements Serializable {

	private static final long serialVersionUID = -1394931224;

	private final String name;

	public Type(Type value) {
		this.name = value.name;
	}

	public Type(
		String name
	) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Type (");

		sb.append(name);

		sb.append(")");
		return sb.toString();
	}
}
