/**
 * This class is generated by jOOQ
 */
package com.thirdchannel.db.tables.records;


import com.thirdchannel.db.tables.People;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeopleRecord extends TableRecordImpl<PeopleRecord> implements Record2<String, String> {

	private static final long serialVersionUID = 376174181;

	/**
	 * Setter for <code>public.people.first_name</code>.
	 */
	public PeopleRecord setFirstName(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.people.first_name</code>.
	 */
	public String getFirstName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.people.last_name</code>.
	 */
	public PeopleRecord setLastName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.people.last_name</code>.
	 */
	public String getLastName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return People.PEOPLE.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return People.PEOPLE.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PeopleRecord value1(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PeopleRecord value2(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PeopleRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PeopleRecord
	 */
	public PeopleRecord() {
		super(People.PEOPLE);
	}

	/**
	 * Create a detached, initialised PeopleRecord
	 */
	public PeopleRecord(String firstName, String lastName) {
		super(People.PEOPLE);

		setValue(0, firstName);
		setValue(1, lastName);
	}
}
